package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="proyecto_uni"
    , uniqueConstraints = @UniqueConstraint(columnNames="Documento") 
)
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String razonSocial;
     private String documento;
     private String direccion;
     private String tipo;
     private String estado;
     private Set ventaCabeceraTemps = new HashSet(0);
     private Set ventaCabeceras = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String documento, String estado) {
        this.documento = documento;
        this.estado = estado;
    }
    public Cliente(String razonSocial, String documento, String direccion, String tipo, String estado, Set ventaCabeceraTemps, Set ventaCabeceras) {
       this.razonSocial = razonSocial;
       this.documento = documento;
       this.direccion = direccion;
       this.tipo = tipo;
       this.estado = estado;
       this.ventaCabeceraTemps = ventaCabeceraTemps;
       this.ventaCabeceras = ventaCabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="RazonSocial", length=250)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="Documento", unique=true, nullable=false, length=11)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    
    @Column(name="Direccion", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Tipo", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getVentaCabeceraTemps() {
        return this.ventaCabeceraTemps;
    }
    
    public void setVentaCabeceraTemps(Set ventaCabeceraTemps) {
        this.ventaCabeceraTemps = ventaCabeceraTemps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getVentaCabeceras() {
        return this.ventaCabeceras;
    }
    
    public void setVentaCabeceras(Set ventaCabeceras) {
        this.ventaCabeceras = ventaCabeceras;
    }




}


