package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String razonSocial;
     private String documento;
     private String direccion;
     private String tipo;
     private Set ventaCabeceraTemps = new HashSet(0);
     private Set ventaCabeceras = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String documento) {
        this.documento = documento;
    }
    public Cliente(String razonSocial, String documento, String direccion, String tipo, Set ventaCabeceraTemps, Set ventaCabeceras) {
       this.razonSocial = razonSocial;
       this.documento = documento;
       this.direccion = direccion;
       this.tipo = tipo;
       this.ventaCabeceraTemps = ventaCabeceraTemps;
       this.ventaCabeceras = ventaCabeceras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getVentaCabeceraTemps() {
        return this.ventaCabeceraTemps;
    }
    
    public void setVentaCabeceraTemps(Set ventaCabeceraTemps) {
        this.ventaCabeceraTemps = ventaCabeceraTemps;
    }
    public Set getVentaCabeceras() {
        return this.ventaCabeceras;
    }
    
    public void setVentaCabeceras(Set ventaCabeceras) {
        this.ventaCabeceras = ventaCabeceras;
    }




}


