package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Consultarucdni generated by hbm2java
 */
@Entity
@Table(name="consultarucdni"
    ,catalog="proyecto_uni"
)
public class Consultarucdni  implements java.io.Serializable {


     private int tipoConsulta;
     private String numero;
     private Integer minChar;
     private Integer maxChar;

    public Consultarucdni() {
    }

	
    public Consultarucdni(int tipoConsulta) {
        this.tipoConsulta = tipoConsulta;
    }
    public Consultarucdni(int tipoConsulta, String numero, Integer minChar, Integer maxChar) {
       this.tipoConsulta = tipoConsulta;
       this.numero = numero;
       this.minChar = minChar;
       this.maxChar = maxChar;
    }
   
     @Id 

    
    @Column(name="tipoConsulta", unique=true, nullable=false)
    public int getTipoConsulta() {
        return this.tipoConsulta;
    }
    
    public void setTipoConsulta(int tipoConsulta) {
        this.tipoConsulta = tipoConsulta;
    }

    
    @Column(name="numero", length=11)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="minChar")
    public Integer getMinChar() {
        return this.minChar;
    }
    
    public void setMinChar(Integer minChar) {
        this.minChar = minChar;
    }

    
    @Column(name="maxChar")
    public Integer getMaxChar() {
        return this.maxChar;
    }
    
    public void setMaxChar(Integer maxChar) {
        this.maxChar = maxChar;
    }




}


