package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Kardexventas generated by hbm2java
 */
public class Kardexventas  implements java.io.Serializable {


     private int id;
     private Integer secuencia;
     private Integer idTipoMov;
     private Integer item;
     private String codpro;
     private BigDecimal stkini;
     private BigDecimal stkmov;
     private BigDecimal stkfin;
     private Integer idUsuario;
     private Date fechaRegistro;
     private BigDecimal precioCompra;
     private BigDecimal precioVenta;

    public Kardexventas() {
    }

	
    public Kardexventas(int id, String codpro, BigDecimal stkini, BigDecimal stkmov, BigDecimal stkfin, Date fechaRegistro, BigDecimal precioCompra, BigDecimal precioVenta) {
        this.id = id;
        this.codpro = codpro;
        this.stkini = stkini;
        this.stkmov = stkmov;
        this.stkfin = stkfin;
        this.fechaRegistro = fechaRegistro;
        this.precioCompra = precioCompra;
        this.precioVenta = precioVenta;
    }
    public Kardexventas(int id, Integer secuencia, Integer idTipoMov, Integer item, String codpro, BigDecimal stkini, BigDecimal stkmov, BigDecimal stkfin, Integer idUsuario, Date fechaRegistro, BigDecimal precioCompra, BigDecimal precioVenta) {
       this.id = id;
       this.secuencia = secuencia;
       this.idTipoMov = idTipoMov;
       this.item = item;
       this.codpro = codpro;
       this.stkini = stkini;
       this.stkmov = stkmov;
       this.stkfin = stkfin;
       this.idUsuario = idUsuario;
       this.fechaRegistro = fechaRegistro;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }
    public Integer getIdTipoMov() {
        return this.idTipoMov;
    }
    
    public void setIdTipoMov(Integer idTipoMov) {
        this.idTipoMov = idTipoMov;
    }
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }
    public String getCodpro() {
        return this.codpro;
    }
    
    public void setCodpro(String codpro) {
        this.codpro = codpro;
    }
    public BigDecimal getStkini() {
        return this.stkini;
    }
    
    public void setStkini(BigDecimal stkini) {
        this.stkini = stkini;
    }
    public BigDecimal getStkmov() {
        return this.stkmov;
    }
    
    public void setStkmov(BigDecimal stkmov) {
        this.stkmov = stkmov;
    }
    public BigDecimal getStkfin() {
        return this.stkfin;
    }
    
    public void setStkfin(BigDecimal stkfin) {
        this.stkfin = stkfin;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }




}


