package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kardexventas generated by hbm2java
 */
@Entity
@Table(name="kardexventas"
    ,catalog="proyecto_uni"
)
public class Kardexventas  implements java.io.Serializable {


     private int id;
     private Integer secuencia;
     private Integer idTipoMov;
     private Integer item;
     private String codpro;
     private BigDecimal stkini;
     private BigDecimal stkmov;
     private BigDecimal stkfin;
     private Integer idUsuario;
     private Date fechaRegistro;
     private BigDecimal precioCompra;
     private BigDecimal precioVenta;

    public Kardexventas() {
    }

	
    public Kardexventas(int id, String codpro, BigDecimal stkini, BigDecimal stkmov, BigDecimal stkfin, Date fechaRegistro, BigDecimal precioCompra, BigDecimal precioVenta) {
        this.id = id;
        this.codpro = codpro;
        this.stkini = stkini;
        this.stkmov = stkmov;
        this.stkfin = stkfin;
        this.fechaRegistro = fechaRegistro;
        this.precioCompra = precioCompra;
        this.precioVenta = precioVenta;
    }
    public Kardexventas(int id, Integer secuencia, Integer idTipoMov, Integer item, String codpro, BigDecimal stkini, BigDecimal stkmov, BigDecimal stkfin, Integer idUsuario, Date fechaRegistro, BigDecimal precioCompra, BigDecimal precioVenta) {
       this.id = id;
       this.secuencia = secuencia;
       this.idTipoMov = idTipoMov;
       this.item = item;
       this.codpro = codpro;
       this.stkini = stkini;
       this.stkmov = stkmov;
       this.stkfin = stkfin;
       this.idUsuario = idUsuario;
       this.fechaRegistro = fechaRegistro;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Secuencia")
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }

    
    @Column(name="IdTipoMov")
    public Integer getIdTipoMov() {
        return this.idTipoMov;
    }
    
    public void setIdTipoMov(Integer idTipoMov) {
        this.idTipoMov = idTipoMov;
    }

    
    @Column(name="item")
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }

    
    @Column(name="Codpro", nullable=false, length=6)
    public String getCodpro() {
        return this.codpro;
    }
    
    public void setCodpro(String codpro) {
        this.codpro = codpro;
    }

    
    @Column(name="stkini", nullable=false, precision=18, scale=3)
    public BigDecimal getStkini() {
        return this.stkini;
    }
    
    public void setStkini(BigDecimal stkini) {
        this.stkini = stkini;
    }

    
    @Column(name="stkmov", nullable=false, precision=18, scale=3)
    public BigDecimal getStkmov() {
        return this.stkmov;
    }
    
    public void setStkmov(BigDecimal stkmov) {
        this.stkmov = stkmov;
    }

    
    @Column(name="stkfin", nullable=false, precision=18, scale=3)
    public BigDecimal getStkfin() {
        return this.stkfin;
    }
    
    public void setStkfin(BigDecimal stkfin) {
        this.stkfin = stkfin;
    }

    
    @Column(name="IdUsuario")
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="PrecioCompra", nullable=false, precision=18, scale=3)
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }

    
    @Column(name="PrecioVenta", nullable=false, precision=18, scale=3)
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }




}


