package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MantenimientoPrecio generated by hbm2java
 */
@Entity
@Table(name="mantenimiento_precio"
    ,catalog="proyecto_uni"
)
public class MantenimientoPrecio  implements java.io.Serializable {


     private Integer secuencia;
     private int porAdministrativo;
     private int porUtilidad;
     private Date fecRegistro;
     private Date fecActualizado;
     private String estado;

    public MantenimientoPrecio() {
    }

	
    public MantenimientoPrecio(int porAdministrativo, int porUtilidad, Date fecRegistro, String estado) {
        this.porAdministrativo = porAdministrativo;
        this.porUtilidad = porUtilidad;
        this.fecRegistro = fecRegistro;
        this.estado = estado;
    }
    public MantenimientoPrecio(int porAdministrativo, int porUtilidad, Date fecRegistro, Date fecActualizado, String estado) {
       this.porAdministrativo = porAdministrativo;
       this.porUtilidad = porUtilidad;
       this.fecRegistro = fecRegistro;
       this.fecActualizado = fecActualizado;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="secuencia", unique=true, nullable=false)
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }

    
    @Column(name="porAdministrativo", nullable=false)
    public int getPorAdministrativo() {
        return this.porAdministrativo;
    }
    
    public void setPorAdministrativo(int porAdministrativo) {
        this.porAdministrativo = porAdministrativo;
    }

    
    @Column(name="porUtilidad", nullable=false)
    public int getPorUtilidad() {
        return this.porUtilidad;
    }
    
    public void setPorUtilidad(int porUtilidad) {
        this.porUtilidad = porUtilidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FecRegistro", nullable=false, length=19)
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FecActualizado", length=19)
    public Date getFecActualizado() {
        return this.fecActualizado;
    }
    
    public void setFecActualizado(Date fecActualizado) {
        this.fecActualizado = fecActualizado;
    }

    
    @Column(name="Estado", nullable=false, length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


