package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MantenimientoPrecio generated by hbm2java
 */
public class MantenimientoPrecio  implements java.io.Serializable {


     private Integer secuencia;
     private int porAdministrativo;
     private int porUtilidad;
     private Date fecRegistro;
     private Date fecActualizado;
     private byte flgEstado;

    public MantenimientoPrecio() {
    }

	
    public MantenimientoPrecio(int porAdministrativo, int porUtilidad, Date fecRegistro, byte flgEstado) {
        this.porAdministrativo = porAdministrativo;
        this.porUtilidad = porUtilidad;
        this.fecRegistro = fecRegistro;
        this.flgEstado = flgEstado;
    }
    public MantenimientoPrecio(int porAdministrativo, int porUtilidad, Date fecRegistro, Date fecActualizado, byte flgEstado) {
       this.porAdministrativo = porAdministrativo;
       this.porUtilidad = porUtilidad;
       this.fecRegistro = fecRegistro;
       this.fecActualizado = fecActualizado;
       this.flgEstado = flgEstado;
    }
   
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }
    public int getPorAdministrativo() {
        return this.porAdministrativo;
    }
    
    public void setPorAdministrativo(int porAdministrativo) {
        this.porAdministrativo = porAdministrativo;
    }
    public int getPorUtilidad() {
        return this.porUtilidad;
    }
    
    public void setPorUtilidad(int porUtilidad) {
        this.porUtilidad = porUtilidad;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public Date getFecActualizado() {
        return this.fecActualizado;
    }
    
    public void setFecActualizado(Date fecActualizado) {
        this.fecActualizado = fecActualizado;
    }
    public byte getFlgEstado() {
        return this.flgEstado;
    }
    
    public void setFlgEstado(byte flgEstado) {
        this.flgEstado = flgEstado;
    }




}


