package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1



/**
 * Pagina generated by hbm2java
 */
public class Pagina  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String url;
     private String idPadre;
     private String icono;
     private Integer orden;
     private String estado;

    public Pagina() {
    }

	
    public Pagina(int id, String idPadre, String estado) {
        this.id = id;
        this.idPadre = idPadre;
        this.estado = estado;
    }
    public Pagina(int id, String nombre, String url, String idPadre, String icono, Integer orden, String estado) {
       this.id = id;
       this.nombre = nombre;
       this.url = url;
       this.idPadre = idPadre;
       this.icono = icono;
       this.orden = orden;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIdPadre() {
        return this.idPadre;
    }
    
    public void setIdPadre(String idPadre) {
        this.idPadre = idPadre;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


