package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pagina generated by hbm2java
 */
@Entity
@Table(name="pagina"
    ,catalog="proyecto_uni"
)
public class Pagina  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String url;
     private String idPadre;
     private String icono;
     private Integer orden;
     private String estado;

    public Pagina() {
    }

	
    public Pagina(int id, String idPadre, String estado) {
        this.id = id;
        this.idPadre = idPadre;
        this.estado = estado;
    }
    public Pagina(int id, String nombre, String url, String idPadre, String icono, Integer orden, String estado) {
       this.id = id;
       this.nombre = nombre;
       this.url = url;
       this.idPadre = idPadre;
       this.icono = icono;
       this.orden = orden;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="url", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="idPadre", nullable=false, length=4)
    public String getIdPadre() {
        return this.idPadre;
    }
    
    public void setIdPadre(String idPadre) {
        this.idPadre = idPadre;
    }

    
    @Column(name="Icono", length=45)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }

    
    @Column(name="Orden")
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


