package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1



/**
 * Paginausuario generated by hbm2java
 */
public class Paginausuario  implements java.io.Serializable {


     private Integer idPaginaUsuario;
     private Integer idPagina;
     private Integer idUsuario;
     private String estado;

    public Paginausuario() {
    }

	
    public Paginausuario(String estado) {
        this.estado = estado;
    }
    public Paginausuario(Integer idPagina, Integer idUsuario, String estado) {
       this.idPagina = idPagina;
       this.idUsuario = idUsuario;
       this.estado = estado;
    }
   
    public Integer getIdPaginaUsuario() {
        return this.idPaginaUsuario;
    }
    
    public void setIdPaginaUsuario(Integer idPaginaUsuario) {
        this.idPaginaUsuario = idPaginaUsuario;
    }
    public Integer getIdPagina() {
        return this.idPagina;
    }
    
    public void setIdPagina(Integer idPagina) {
        this.idPagina = idPagina;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


