package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productoserie generated by hbm2java
 */
public class Productoserie  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private String nroSerie;
     private BigDecimal precioCompra;
     private Date fechaCreado;
     private int disponible;
     private String estado;
     private Set ventaDetalleTemps = new HashSet(0);
     private Set ventaDetalles = new HashSet(0);

    public Productoserie() {
    }

	
    public Productoserie(Date fechaCreado, int disponible, String estado) {
        this.fechaCreado = fechaCreado;
        this.disponible = disponible;
        this.estado = estado;
    }
    public Productoserie(Producto producto, String nroSerie, BigDecimal precioCompra, Date fechaCreado, int disponible, String estado, Set ventaDetalleTemps, Set ventaDetalles) {
       this.producto = producto;
       this.nroSerie = nroSerie;
       this.precioCompra = precioCompra;
       this.fechaCreado = fechaCreado;
       this.disponible = disponible;
       this.estado = estado;
       this.ventaDetalleTemps = ventaDetalleTemps;
       this.ventaDetalles = ventaDetalles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getNroSerie() {
        return this.nroSerie;
    }
    
    public void setNroSerie(String nroSerie) {
        this.nroSerie = nroSerie;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Date getFechaCreado() {
        return this.fechaCreado;
    }
    
    public void setFechaCreado(Date fechaCreado) {
        this.fechaCreado = fechaCreado;
    }
    public int getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(int disponible) {
        this.disponible = disponible;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentaDetalleTemps() {
        return this.ventaDetalleTemps;
    }
    
    public void setVentaDetalleTemps(Set ventaDetalleTemps) {
        this.ventaDetalleTemps = ventaDetalleTemps;
    }
    public Set getVentaDetalles() {
        return this.ventaDetalles;
    }
    
    public void setVentaDetalles(Set ventaDetalles) {
        this.ventaDetalles = ventaDetalles;
    }




}


