package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String codpro;
     private Categoria categoria;
     private Marca marca;
     private String descripcion;
     private String especificacion;
     private BigDecimal precioCompra;
     private String imagen;
     private Date fechaCreado;
     private String estado;
     private Set productoseries = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String codpro, Date fechaCreado, String estado) {
        this.codpro = codpro;
        this.fechaCreado = fechaCreado;
        this.estado = estado;
    }
    public Producto(String codpro, Categoria categoria, Marca marca, String descripcion, String especificacion, BigDecimal precioCompra, String imagen, Date fechaCreado, String estado, Set productoseries) {
       this.codpro = codpro;
       this.categoria = categoria;
       this.marca = marca;
       this.descripcion = descripcion;
       this.especificacion = especificacion;
       this.precioCompra = precioCompra;
       this.imagen = imagen;
       this.fechaCreado = fechaCreado;
       this.estado = estado;
       this.productoseries = productoseries;
    }
   
    public String getCodpro() {
        return this.codpro;
    }
    
    public void setCodpro(String codpro) {
        this.codpro = codpro;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEspecificacion() {
        return this.especificacion;
    }
    
    public void setEspecificacion(String especificacion) {
        this.especificacion = especificacion;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Date getFechaCreado() {
        return this.fechaCreado;
    }
    
    public void setFechaCreado(Date fechaCreado) {
        this.fechaCreado = fechaCreado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductoseries() {
        return this.productoseries;
    }
    
    public void setProductoseries(Set productoseries) {
        this.productoseries = productoseries;
    }




}


