package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="proyecto_uni"
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String rucprv;
     private String razonSocial;
     private String estado;

    public Proveedor() {
    }

    public Proveedor(int idProveedor, String rucprv, String razonSocial, String estado) {
       this.idProveedor = idProveedor;
       this.rucprv = rucprv;
       this.razonSocial = razonSocial;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="idProveedor", unique=true, nullable=false)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="Rucprv", nullable=false, length=11)
    public String getRucprv() {
        return this.rucprv;
    }
    
    public void setRucprv(String rucprv) {
        this.rucprv = rucprv;
    }

    
    @Column(name="RazonSocial", nullable=false)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


