package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String rucprv;
     private String razonSocial;
     private String estado;

    public Proveedor() {
    }

    public Proveedor(int idProveedor, String rucprv, String razonSocial, String estado) {
       this.idProveedor = idProveedor;
       this.rucprv = rucprv;
       this.razonSocial = razonSocial;
       this.estado = estado;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getRucprv() {
        return this.rucprv;
    }
    
    public void setRucprv(String rucprv) {
        this.rucprv = rucprv;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


