package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer id;
     private String nombreRol;
     private String flgEstado;
     private String tipRol;
     private int leer;
     private int agregar;
     private int editar;
     private int eliminar;
     private int facturar;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }	
    public Rol(String flgEstado, String tipRol, int leer, int agregar, int editar, int eliminar, int facturar) {
        this.flgEstado = flgEstado;
        this.tipRol = tipRol;
        this.leer = leer;
        this.agregar = agregar;
        this.editar = editar;
        this.eliminar = eliminar;
        this.facturar = facturar;
    }
    public Rol(String nombreRol, String flgEstado, String tipRol, int leer, int agregar, int editar, int eliminar, int facturar, Set usuarios) {
       this.nombreRol = nombreRol;
       this.flgEstado = flgEstado;
       this.tipRol = tipRol;
       this.leer = leer;
       this.agregar = agregar;
       this.editar = editar;
       this.eliminar = eliminar;
       this.facturar = facturar;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public String getFlgEstado() {
        return this.flgEstado;
    }
    
    public void setFlgEstado(String flgEstado) {
        this.flgEstado = flgEstado;
    }
    public String getTipRol() {
        return this.tipRol;
    }
    
    public void setTipRol(String tipRol) {
        this.tipRol = tipRol;
    }
    public int getLeer() {
        return this.leer;
    }
    
    public void setLeer(int leer) {
        this.leer = leer;
    }
    public int getAgregar() {
        return this.agregar;
    }
    
    public void setAgregar(int agregar) {
        this.agregar = agregar;
    }
    public int getEditar() {
        return this.editar;
    }
    
    public void setEditar(int editar) {
        this.editar = editar;
    }
    public int getEliminar() {
        return this.eliminar;
    }
    
    public void setEliminar(int eliminar) {
        this.eliminar = eliminar;
    }
    public int getFacturar() {
        return this.facturar;
    }
    
    public void setFacturar(int facturar) {
        this.facturar = facturar;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


