package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,catalog="proyecto_uni"
)
public class Rol  implements java.io.Serializable {


     private Integer id;
     private String nombreRol;
     private String flgEstado;
     private String tipRol;
     private int leer;
     private int agregar;
     private int editar;
     private int eliminar;
     private int facturar;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String flgEstado, String tipRol, int leer, int agregar, int editar, int eliminar, int facturar) {
        this.flgEstado = flgEstado;
        this.tipRol = tipRol;
        this.leer = leer;
        this.agregar = agregar;
        this.editar = editar;
        this.eliminar = eliminar;
        this.facturar = facturar;
    }
    public Rol(String nombreRol, String flgEstado, String tipRol, int leer, int agregar, int editar, int eliminar, int facturar, Set usuarios) {
       this.nombreRol = nombreRol;
       this.flgEstado = flgEstado;
       this.tipRol = tipRol;
       this.leer = leer;
       this.agregar = agregar;
       this.editar = editar;
       this.eliminar = eliminar;
       this.facturar = facturar;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NombreRol", length=45)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

    
    @Column(name="FlgEstado", nullable=false, length=2)
    public String getFlgEstado() {
        return this.flgEstado;
    }
    
    public void setFlgEstado(String flgEstado) {
        this.flgEstado = flgEstado;
    }

    
    @Column(name="TipRol", nullable=false, length=2)
    public String getTipRol() {
        return this.tipRol;
    }
    
    public void setTipRol(String tipRol) {
        this.tipRol = tipRol;
    }

    
    @Column(name="Leer", nullable=false)
    public int getLeer() {
        return this.leer;
    }
    
    public void setLeer(int leer) {
        this.leer = leer;
    }

    
    @Column(name="Agregar", nullable=false)
    public int getAgregar() {
        return this.agregar;
    }
    
    public void setAgregar(int agregar) {
        this.agregar = agregar;
    }

    
    @Column(name="Editar", nullable=false)
    public int getEditar() {
        return this.editar;
    }
    
    public void setEditar(int editar) {
        this.editar = editar;
    }

    
    @Column(name="Eliminar", nullable=false)
    public int getEliminar() {
        return this.eliminar;
    }
    
    public void setEliminar(int eliminar) {
        this.eliminar = eliminar;
    }

    
    @Column(name="Facturar", nullable=false)
    public int getFacturar() {
        return this.facturar;
    }
    
    public void setFacturar(int facturar) {
        this.facturar = facturar;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


