package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipocomprobante generated by hbm2java
 */
public class Tipocomprobante  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int codigo;
     private String estado;
     private Set usuarioseries = new HashSet(0);

    public Tipocomprobante() {
    }

	
    public Tipocomprobante(String nombre, int codigo, String estado) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.estado = estado;
    }
    public Tipocomprobante(String nombre, int codigo, String estado, Set usuarioseries) {
       this.nombre = nombre;
       this.codigo = codigo;
       this.estado = estado;
       this.usuarioseries = usuarioseries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getUsuarioseries() {
        return this.usuarioseries;
    }
    
    public void setUsuarioseries(Set usuarioseries) {
        this.usuarioseries = usuarioseries;
    }




}


