package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name="tipomovimiento"
    ,catalog="proyecto_uni"
)
public class Tipomovimiento  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String estado;

    public Tipomovimiento() {
    }

    public Tipomovimiento(int id, String nombre, String estado) {
       this.id = id;
       this.nombre = nombre;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


