package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocomprobante generated by hbm2java
 */
@Entity
@Table(name="tipocomprobante"
    ,catalog="proyecto_uni"
)
public class Tipocomprobante  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int codigo;
     private String estado;
     private Set usuarioseries = new HashSet(0);

    public Tipocomprobante() {
    }

	
    public Tipocomprobante(String nombre, int codigo, String estado) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.estado = estado;
    }
    public Tipocomprobante(String nombre, int codigo, String estado, Set usuarioseries) {
       this.nombre = nombre;
       this.codigo = codigo;
       this.estado = estado;
       this.usuarioseries = usuarioseries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="codigo", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipocomprobante")
    public Set getUsuarioseries() {
        return this.usuarioseries;
    }
    
    public void setUsuarioseries(Set usuarioseries) {
        this.usuarioseries = usuarioseries;
    }




}


