package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1



/**
 * Tipodocumentoidentidad generated by hbm2java
 */
public class Tipodocumentoidentidad  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private String estado;
     private Integer codigo;

    public Tipodocumentoidentidad() {
    }

	
    public Tipodocumentoidentidad(String descripcion, String estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Tipodocumentoidentidad(String descripcion, String estado, Integer codigo) {
       this.descripcion = descripcion;
       this.estado = estado;
       this.codigo = codigo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }




}


