package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1



/**
 * Tipomovimiento generated by hbm2java
 */
public class Tipomovimiento  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String estado;

    public Tipomovimiento() {
    }

    public Tipomovimiento(int id, String nombre, String estado) {
       this.id = id;
       this.nombre = nombre;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


