package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuarioserie generated by hbm2java
 */
@Entity
@Table(name="usuarioserie"
    ,catalog="proyecto_uni"
)
public class Usuarioserie  implements java.io.Serializable {


     private Integer id;
     private Tipocomprobante tipocomprobante;
     private Usuario usuario;
     private String nroSerie;
     private String estado;

    public Usuarioserie() {
    }

	
    public Usuarioserie(Tipocomprobante tipocomprobante, String nroSerie, String estado) {
        this.tipocomprobante = tipocomprobante;
        this.nroSerie = nroSerie;
        this.estado = estado;
    }
    public Usuarioserie(Tipocomprobante tipocomprobante, Usuario usuario, String nroSerie, String estado) {
       this.tipocomprobante = tipocomprobante;
       this.usuario = usuario;
       this.nroSerie = nroSerie;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdTipoComprobante", nullable=false)
    public Tipocomprobante getTipocomprobante() {
        return this.tipocomprobante;
    }
    
    public void setTipocomprobante(Tipocomprobante tipocomprobante) {
        this.tipocomprobante = tipocomprobante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUsuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="NroSerie", nullable=false, length=5)
    public String getNroSerie() {
        return this.nroSerie;
    }
    
    public void setNroSerie(String nroSerie) {
        this.nroSerie = nroSerie;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


