package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="proyecto_uni"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Rol rol;
     private String nombre;
     private String apellidos;
     private String email;
     private String password;
     private String estado;
     private Set usuarioseries = new HashSet(0);

    public Usuario() {
        rol=new Rol();
    }

	
    public Usuario(String nombre, String estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Usuario(Rol rol, String nombre, String email, String password, String estado, Set usuarioseries) {
       this.rol = rol;
       this.nombre = nombre;
       this.email = email;
       this.password = password;
       this.estado = estado;
       this.usuarioseries = usuarioseries;
    }
    public Usuario(Rol rol, String nombre, String apellidos, String email, String password, String estado, Set usuarioseries) {
       this.rol = rol;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.password = password;
       this.estado = estado;
       this.usuarioseries = usuarioseries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdRol")
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="apellidos", length=100)
    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="email", unique=true, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getUsuarioseries() {
        return this.usuarioseries;
    }
    
    public void setUsuarioseries(Set usuarioseries) {
        this.usuarioseries = usuarioseries;
    }




}


