package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1



/**
 * Usuarioserie generated by hbm2java
 */
public class Usuarioserie  implements java.io.Serializable {


     private Integer id;
     private Tipocomprobante tipocomprobante;
     private Usuario usuario;
     private String nroSerie;
     private String estado;

    public Usuarioserie() {
    }

	
    public Usuarioserie(Tipocomprobante tipocomprobante, String nroSerie, String estado) {
        this.tipocomprobante = tipocomprobante;
        this.nroSerie = nroSerie;
        this.estado = estado;
    }
    public Usuarioserie(Tipocomprobante tipocomprobante, Usuario usuario, String nroSerie, String estado) {
       this.tipocomprobante = tipocomprobante;
       this.usuario = usuario;
       this.nroSerie = nroSerie;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipocomprobante getTipocomprobante() {
        return this.tipocomprobante;
    }
    
    public void setTipocomprobante(Tipocomprobante tipocomprobante) {
        this.tipocomprobante = tipocomprobante;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNroSerie() {
        return this.nroSerie;
    }
    
    public void setNroSerie(String nroSerie) {
        this.nroSerie = nroSerie;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


