package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer id;
    private Rol rol;
    private String nombre;
    private String email;
    private String password;
    private String estado;
    private Set usuarioseries = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nombre, String estado) {
        this.nombre = nombre;
        this.estado = estado;
    }

    public Usuario(Rol rol, String nombre, String email, String password, String estado, Set usuarioseries) {
        this.rol = rol;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.estado = estado;
        this.usuarioseries = usuarioseries;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Set getUsuarioseries() {
        return this.usuarioseries;
    }

    public void setUsuarioseries(Set usuarioseries) {
        this.usuarioseries = usuarioseries;
    }
}
