package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VentaCabecera generated by hbm2java
 */
public class VentaCabecera  implements java.io.Serializable {


     private int secuencia;
     private Cliente cliente;
     private Integer tipoComprobante;
     private String serieDoc;
     private String numeroDoc;
     private BigDecimal impTotal;
     private BigDecimal imgIgv;
     private BigDecimal impSubTotal;
     private String flgEstado;
     private String flgActivo;
     private Date fecRegistro;
     private Date fecEntrega;
     private Set ventaDetalles = new HashSet(0);

    public VentaCabecera() {
    }

	
    public VentaCabecera(int secuencia, String flgEstado, String flgActivo, Date fecRegistro) {
        this.secuencia = secuencia;
        this.flgEstado = flgEstado;
        this.flgActivo = flgActivo;
        this.fecRegistro = fecRegistro;
    }
    public VentaCabecera(int secuencia, Cliente cliente, Integer tipoComprobante, String serieDoc, String numeroDoc, BigDecimal impTotal, BigDecimal imgIgv, BigDecimal impSubTotal, String flgEstado, String flgActivo, Date fecRegistro, Date fecEntrega, Set ventaDetalles) {
       this.secuencia = secuencia;
       this.cliente = cliente;
       this.tipoComprobante = tipoComprobante;
       this.serieDoc = serieDoc;
       this.numeroDoc = numeroDoc;
       this.impTotal = impTotal;
       this.imgIgv = imgIgv;
       this.impSubTotal = impSubTotal;
       this.flgEstado = flgEstado;
       this.flgActivo = flgActivo;
       this.fecRegistro = fecRegistro;
       this.fecEntrega = fecEntrega;
       this.ventaDetalles = ventaDetalles;
    }
   
    public int getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(int secuencia) {
        this.secuencia = secuencia;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(Integer tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public String getSerieDoc() {
        return this.serieDoc;
    }
    
    public void setSerieDoc(String serieDoc) {
        this.serieDoc = serieDoc;
    }
    public String getNumeroDoc() {
        return this.numeroDoc;
    }
    
    public void setNumeroDoc(String numeroDoc) {
        this.numeroDoc = numeroDoc;
    }
    public BigDecimal getImpTotal() {
        return this.impTotal;
    }
    
    public void setImpTotal(BigDecimal impTotal) {
        this.impTotal = impTotal;
    }
    public BigDecimal getImgIgv() {
        return this.imgIgv;
    }
    
    public void setImgIgv(BigDecimal imgIgv) {
        this.imgIgv = imgIgv;
    }
    public BigDecimal getImpSubTotal() {
        return this.impSubTotal;
    }
    
    public void setImpSubTotal(BigDecimal impSubTotal) {
        this.impSubTotal = impSubTotal;
    }
    public String getFlgEstado() {
        return this.flgEstado;
    }
    
    public void setFlgEstado(String flgEstado) {
        this.flgEstado = flgEstado;
    }
    public String getFlgActivo() {
        return this.flgActivo;
    }
    
    public void setFlgActivo(String flgActivo) {
        this.flgActivo = flgActivo;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public Date getFecEntrega() {
        return this.fecEntrega;
    }
    
    public void setFecEntrega(Date fecEntrega) {
        this.fecEntrega = fecEntrega;
    }
    public Set getVentaDetalles() {
        return this.ventaDetalles;
    }
    
    public void setVentaDetalles(Set ventaDetalles) {
        this.ventaDetalles = ventaDetalles;
    }




}


