package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VentaDetalleTemp generated by hbm2java
 */
public class VentaDetalleTemp  implements java.io.Serializable {


     private VentaDetalleTempId id;
     private Productoserie productoserie;
     private VentaCabeceraTemp ventaCabeceraTemp;
     private BigDecimal precioVenta;
     private String afecto;

    public VentaDetalleTemp() {
    }

	
    public VentaDetalleTemp(VentaDetalleTempId id, VentaCabeceraTemp ventaCabeceraTemp) {
        this.id = id;
        this.ventaCabeceraTemp = ventaCabeceraTemp;
    }
    public VentaDetalleTemp(VentaDetalleTempId id, Productoserie productoserie, VentaCabeceraTemp ventaCabeceraTemp, BigDecimal precioVenta, String afecto) {
       this.id = id;
       this.productoserie = productoserie;
       this.ventaCabeceraTemp = ventaCabeceraTemp;
       this.precioVenta = precioVenta;
       this.afecto = afecto;
    }
   
    public VentaDetalleTempId getId() {
        return this.id;
    }
    
    public void setId(VentaDetalleTempId id) {
        this.id = id;
    }
    public Productoserie getProductoserie() {
        return this.productoserie;
    }
    
    public void setProductoserie(Productoserie productoserie) {
        this.productoserie = productoserie;
    }
    public VentaCabeceraTemp getVentaCabeceraTemp() {
        return this.ventaCabeceraTemp;
    }
    
    public void setVentaCabeceraTemp(VentaCabeceraTemp ventaCabeceraTemp) {
        this.ventaCabeceraTemp = ventaCabeceraTemp;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public String getAfecto() {
        return this.afecto;
    }
    
    public void setAfecto(String afecto) {
        this.afecto = afecto;
    }




}


