package com.entidad;
// Generated 15-jun-2023 8:30:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VentaDetalle generated by hbm2java
 */
public class VentaDetalle  implements java.io.Serializable {


     private VentaDetalleId id;
     private Productoserie productoserie;
     private VentaCabecera ventaCabecera;
     private BigDecimal precioVenta;
     private String afecto;

    public VentaDetalle() {
    }

	
    public VentaDetalle(VentaDetalleId id, VentaCabecera ventaCabecera) {
        this.id = id;
        this.ventaCabecera = ventaCabecera;
    }
    public VentaDetalle(VentaDetalleId id, Productoserie productoserie, VentaCabecera ventaCabecera, BigDecimal precioVenta, String afecto) {
       this.id = id;
       this.productoserie = productoserie;
       this.ventaCabecera = ventaCabecera;
       this.precioVenta = precioVenta;
       this.afecto = afecto;
    }
   
    public VentaDetalleId getId() {
        return this.id;
    }
    
    public void setId(VentaDetalleId id) {
        this.id = id;
    }
    public Productoserie getProductoserie() {
        return this.productoserie;
    }
    
    public void setProductoserie(Productoserie productoserie) {
        this.productoserie = productoserie;
    }
    public VentaCabecera getVentaCabecera() {
        return this.ventaCabecera;
    }
    
    public void setVentaCabecera(VentaCabecera ventaCabecera) {
        this.ventaCabecera = ventaCabecera;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public String getAfecto() {
        return this.afecto;
    }
    
    public void setAfecto(String afecto) {
        this.afecto = afecto;
    }




}


