package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VentaDetalleTemp generated by hbm2java
 */
@Entity
@Table(name="venta_detalle_temp"
    ,catalog="proyecto_uni"
)
public class VentaDetalleTemp  implements java.io.Serializable {


     private VentaDetalleTempId id;
     private Productoserie productoserie;
     private VentaCabeceraTemp ventaCabeceraTemp;
     private BigDecimal precioVenta;
     private String afecto;

    public VentaDetalleTemp() {
    }

	
    public VentaDetalleTemp(VentaDetalleTempId id, VentaCabeceraTemp ventaCabeceraTemp) {
        this.id = id;
        this.ventaCabeceraTemp = ventaCabeceraTemp;
    }
    public VentaDetalleTemp(VentaDetalleTempId id, Productoserie productoserie, VentaCabeceraTemp ventaCabeceraTemp, BigDecimal precioVenta, String afecto) {
       this.id = id;
       this.productoserie = productoserie;
       this.ventaCabeceraTemp = ventaCabeceraTemp;
       this.precioVenta = precioVenta;
       this.afecto = afecto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="secuencia", column=@Column(name="secuencia", nullable=false) ), 
        @AttributeOverride(name="item", column=@Column(name="item", nullable=false) ) } )
    public VentaDetalleTempId getId() {
        return this.id;
    }
    
    public void setId(VentaDetalleTempId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdSerieProducto")
    public Productoserie getProductoserie() {
        return this.productoserie;
    }
    
    public void setProductoserie(Productoserie productoserie) {
        this.productoserie = productoserie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secuencia", nullable=false, insertable=false, updatable=false)
    public VentaCabeceraTemp getVentaCabeceraTemp() {
        return this.ventaCabeceraTemp;
    }
    
    public void setVentaCabeceraTemp(VentaCabeceraTemp ventaCabeceraTemp) {
        this.ventaCabeceraTemp = ventaCabeceraTemp;
    }

    
    @Column(name="precio_venta", precision=18, scale=3)
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="afecto", length=1)
    public String getAfecto() {
        return this.afecto;
    }
    
    public void setAfecto(String afecto) {
        this.afecto = afecto;
    }




}


