package com.entidad;
// Generated 29-jun-2023 22:51:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VentaCabecera generated by hbm2java
 */
@Entity
@Table(name="venta_cabecera"
    ,catalog="proyecto_uni"
)
public class VentaCabecera  implements java.io.Serializable {


     private int secuencia;
     private Cliente cliente;
     private Integer tipoComprobante;
     private String serieDoc;
     private String numeroDoc;
     private BigDecimal impTotal;
     private BigDecimal imgIgv;
     private BigDecimal impSubTotal;
     private String estado;
     private String flgActivo;
     private Date fecRegistro;
     private Date fecEntrega;
     private Set ventaDetalles = new HashSet(0);

    public VentaCabecera() {
    }

	
    public VentaCabecera(int secuencia, String estado, String flgActivo, Date fecRegistro) {
        this.secuencia = secuencia;
        this.estado = estado;
        this.flgActivo = flgActivo;
        this.fecRegistro = fecRegistro;
    }
    public VentaCabecera(int secuencia, Cliente cliente, Integer tipoComprobante, String serieDoc, String numeroDoc, BigDecimal impTotal, BigDecimal imgIgv, BigDecimal impSubTotal, String estado, String flgActivo, Date fecRegistro, Date fecEntrega, Set ventaDetalles) {
       this.secuencia = secuencia;
       this.cliente = cliente;
       this.tipoComprobante = tipoComprobante;
       this.serieDoc = serieDoc;
       this.numeroDoc = numeroDoc;
       this.impTotal = impTotal;
       this.imgIgv = imgIgv;
       this.impSubTotal = impSubTotal;
       this.estado = estado;
       this.flgActivo = flgActivo;
       this.fecRegistro = fecRegistro;
       this.fecEntrega = fecEntrega;
       this.ventaDetalles = ventaDetalles;
    }
   
     @Id 

    
    @Column(name="secuencia", unique=true, nullable=false)
    public int getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(int secuencia) {
        this.secuencia = secuencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCliente")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="TipoComprobante")
    public Integer getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(Integer tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }

    
    @Column(name="Serie_doc", length=4)
    public String getSerieDoc() {
        return this.serieDoc;
    }
    
    public void setSerieDoc(String serieDoc) {
        this.serieDoc = serieDoc;
    }

    
    @Column(name="Numero_doc", length=8)
    public String getNumeroDoc() {
        return this.numeroDoc;
    }
    
    public void setNumeroDoc(String numeroDoc) {
        this.numeroDoc = numeroDoc;
    }

    
    @Column(name="ImpTotal", precision=18, scale=3)
    public BigDecimal getImpTotal() {
        return this.impTotal;
    }
    
    public void setImpTotal(BigDecimal impTotal) {
        this.impTotal = impTotal;
    }

    
    @Column(name="ImgIgv", precision=18, scale=3)
    public BigDecimal getImgIgv() {
        return this.imgIgv;
    }
    
    public void setImgIgv(BigDecimal imgIgv) {
        this.imgIgv = imgIgv;
    }

    
    @Column(name="ImpSubTotal", precision=18, scale=3)
    public BigDecimal getImpSubTotal() {
        return this.impSubTotal;
    }
    
    public void setImpSubTotal(BigDecimal impSubTotal) {
        this.impSubTotal = impSubTotal;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="FlgActivo", nullable=false, length=2)
    public String getFlgActivo() {
        return this.flgActivo;
    }
    
    public void setFlgActivo(String flgActivo) {
        this.flgActivo = flgActivo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FecRegistro", nullable=false, length=19)
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FecEntrega", length=19)
    public Date getFecEntrega() {
        return this.fecEntrega;
    }
    
    public void setFecEntrega(Date fecEntrega) {
        this.fecEntrega = fecEntrega;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ventaCabecera")
    public Set getVentaDetalles() {
        return this.ventaDetalles;
    }
    
    public void setVentaDetalles(Set ventaDetalles) {
        this.ventaDetalles = ventaDetalles;
    }




}


